### PR TITLE
SYMP-109: Update COVID Test Recommendation

### PR DESCRIPTION
**Pull request by ninosamson**

### CODE REVIEW

**Comment by dbayly-freshworks** [comment]
Looks like you need to update `questions.json` in the cypress folder (line 136), with the new title. That should fix the tests.

**Comment by ninosamson** [comment]
Let me try that! Also noticed, the [contents] isn't quite accurate - does that matter @dbayly-freshworks ?

**Comment by dbayly-freshworks** [comment]
> Let me try that! Also noticed, the [contents] isn't quite accurate - does that matter @dbayly-freshworks ?

Yes and no - Its good practice to have content of questions.json match the content of the form.
However, our cypress tests do not check the contents of that paragraph at any point, so it would not change anything functionally.

**Comment by ninosamson** [comment]
Thanks, that did it @dbayly-freshworks !

**Review by dbayly-freshworks — APPROVED** [review]

**Pull request merged**
